"""
Fallback data for tools, agents, and courses
"""
from typing import List, Dict
from config import FALLBACK_IMAGE

TOOLS_FALLBACK: List[Dict] = [
    {"name": "ChatGPT",            "category": "Chatbot",           "pricing": "freemium", "description": "OpenAI's conversational AI for writing, coding, Q&A and brainstorming. The most widely used AI assistant in the world.",                              "url": "https://chat.openai.com",                     "tags": ["text", "coding", "writing"],           "image": FALLBACK_IMAGE},
    {"name": "Claude",             "category": "Chatbot",           "pricing": "freemium", "description": "Anthropic's AI assistant known for thoughtful, nuanced responses. Excellent for long documents, analysis and coding tasks.",                          "url": "https://claude.ai",                           "tags": ["text", "analysis", "coding"],          "image": FALLBACK_IMAGE},
    {"name": "Gemini",             "category": "Chatbot",           "pricing": "freemium", "description": "Google's multimodal AI that integrates with Google Workspace. Understands text, images, audio and video natively.",                                   "url": "https://gemini.google.com",                   "tags": ["text", "multimodal", "google"],         "image": FALLBACK_IMAGE},
    {"name": "Perplexity AI",      "category": "Search",            "pricing": "freemium", "description": "AI-powered search engine that answers questions with cited sources in real time. A smarter alternative to traditional search.",                        "url": "https://perplexity.ai",                       "tags": ["search", "research", "citations"],      "image": FALLBACK_IMAGE},
    {"name": "Midjourney",         "category": "Image Generation",  "pricing": "paid",     "description": "Generate stunning photorealistic and artistic images from text prompts. The gold standard for AI art and design work.",                               "url": "https://midjourney.com",                      "tags": ["image", "design", "art"],              "image": FALLBACK_IMAGE},
    {"name": "DALL·E 3",           "category": "Image Generation",  "pricing": "freemium", "description": "OpenAI's image generator built into ChatGPT. Creates accurate, detailed images from natural language descriptions.",                                  "url": "https://openai.com/dall-e-3",                 "tags": ["image", "openai", "art"],              "image": FALLBACK_IMAGE},
    {"name": "Stable Diffusion",   "category": "Image Generation",  "pricing": "free",     "description": "Open-source image generation model you can run locally or via web UIs. Highly customisable with thousands of community models.",                     "url": "https://stability.ai",                        "tags": ["image", "open-source", "local"],       "image": FALLBACK_IMAGE},
    {"name": "GitHub Copilot",     "category": "Coding",            "pricing": "paid",     "description": "AI pair programmer that autocompletes code, explains functions and generates entire files directly inside your code editor.",                          "url": "https://github.com/features/copilot",         "tags": ["coding", "github", "autocomplete"],    "image": FALLBACK_IMAGE},
    {"name": "Cursor",             "category": "Coding",            "pricing": "freemium", "description": "AI-first code editor built on VS Code. Chat with your codebase, generate features and fix bugs with natural language.",                               "url": "https://cursor.sh",                           "tags": ["coding", "editor", "vscode"],          "image": FALLBACK_IMAGE},
    {"name": "Claude Code",        "category": "Coding",            "pricing": "freemium", "description": "Anthropic's agentic coding tool that runs in your terminal. Understands entire codebases and executes multi-step engineering tasks.",                 "url": "https://claude.ai/code",                      "tags": ["coding", "terminal", "agentic"],       "image": FALLBACK_IMAGE},
    {"name": "Replit AI",          "category": "Coding",            "pricing": "freemium", "description": "AI coding assistant inside Replit's browser IDE. Write, run and deploy code entirely in the cloud with AI assistance.",                              "url": "https://replit.com/ai",                       "tags": ["coding", "browser", "deployment"],     "image": FALLBACK_IMAGE},
    {"name": "v0 by Vercel",       "category": "Coding",            "pricing": "freemium", "description": "Generate React UI components from a text prompt. Paste the code directly into your project — zero setup required.",                                  "url": "https://v0.dev",                              "tags": ["coding", "ui", "react"],               "image": FALLBACK_IMAGE},
    {"name": "Jasper",             "category": "Writing",           "pricing": "paid",     "description": "AI writing platform for marketing teams. Creates blog posts, ad copy, emails and social content at scale with brand voice controls.",                 "url": "https://jasper.ai",                           "tags": ["writing", "marketing", "copywriting"], "image": FALLBACK_IMAGE},
    {"name": "Grammarly",          "category": "Writing",           "pricing": "freemium", "description": "AI writing assistant that checks grammar, tone, clarity and style. Works across browsers, Google Docs and email clients.",                            "url": "https://grammarly.com",                       "tags": ["writing", "grammar", "editing"],       "image": FALLBACK_IMAGE},
    {"name": "Copy.ai",            "category": "Writing",           "pricing": "freemium", "description": "Generate marketing copy, product descriptions, email sequences and blog content in seconds with AI-powered templates.",                               "url": "https://copy.ai",                             "tags": ["writing", "marketing", "copywriting"], "image": FALLBACK_IMAGE},
    {"name": "Runway",             "category": "Video",             "pricing": "freemium", "description": "AI video generation and editing suite. Generate videos from text, remove backgrounds and apply cinematic effects with ease.",                          "url": "https://runwayml.com",                        "tags": ["video", "editing", "generation"],      "image": FALLBACK_IMAGE},
    {"name": "Sora",               "category": "Video",             "pricing": "freemium", "description": "OpenAI's text-to-video model that generates realistic scenes from prompts up to a minute long. Cinematic quality output.",                           "url": "https://sora.com",                            "tags": ["video", "openai", "generation"],       "image": FALLBACK_IMAGE},
    {"name": "Pika",               "category": "Video",             "pricing": "freemium", "description": "Generate and edit videos with AI. Animate images, modify existing clips and create cinematic scenes from a text description.",                        "url": "https://pika.art",                            "tags": ["video", "animation", "generation"],    "image": FALLBACK_IMAGE},
    {"name": "ElevenLabs",         "category": "Audio",             "pricing": "freemium", "description": "AI voice synthesis and cloning. Generate natural-sounding speech in any voice or language for podcasts, videos and apps.",                            "url": "https://elevenlabs.io",                       "tags": ["audio", "voice", "tts"],               "image": FALLBACK_IMAGE},
    {"name": "Suno",               "category": "Audio",             "pricing": "freemium", "description": "Generate full songs with vocals and instruments from a text prompt. Create original music in any genre in seconds.",                                  "url": "https://suno.ai",                             "tags": ["audio", "music", "generation"],        "image": FALLBACK_IMAGE},
    {"name": "Notion AI",          "category": "Productivity",      "pricing": "paid",     "description": "AI built into Notion that summarises pages, drafts content, translates text and answers questions about your workspace.",                             "url": "https://notion.so/product/ai",                "tags": ["productivity", "notes", "workspace"],  "image": FALLBACK_IMAGE},
    {"name": "Otter.ai",           "category": "Productivity",      "pricing": "freemium", "description": "AI meeting assistant that transcribes, summarises and captures action items from meetings in real time across Zoom, Meet and Teams.",                 "url": "https://otter.ai",                            "tags": ["productivity", "transcription", "meetings"], "image": FALLBACK_IMAGE},
    {"name": "Gamma",              "category": "Productivity",      "pricing": "freemium", "description": "Create beautiful presentations, documents and websites with AI. Just describe what you want and Gamma generates a polished deck instantly.",           "url": "https://gamma.app",                           "tags": ["productivity", "presentations", "design"], "image": FALLBACK_IMAGE},
    {"name": "Whisper",            "category": "Audio",             "pricing": "free",     "description": "OpenAI's open-source speech recognition model. Transcribes audio in 99 languages with impressive accuracy. Free to run locally.",                    "url": "https://openai.com/research/whisper",          "tags": ["audio", "transcription", "open-source"], "image": FALLBACK_IMAGE},
    {"name": "Hugging Face",       "category": "Open-Source LLM",  "pricing": "free",     "description": "The hub for open-source AI models, datasets and demos. Home to thousands of community models for every AI task imaginable.",                         "url": "https://huggingface.co",                      "tags": ["open-source", "models", "hub"],        "image": FALLBACK_IMAGE},
    {"name": "Ollama",             "category": "Open-Source LLM",  "pricing": "free",     "description": "Run large language models locally on your own machine with one command. Supports Llama, Mistral, Gemma, Phi and dozens more.",                      "url": "https://ollama.ai",                           "tags": ["open-source", "local", "llm"],         "image": FALLBACK_IMAGE},
    {"name": "LM Studio",          "category": "Open-Source LLM",  "pricing": "free",     "description": "Desktop app for discovering, downloading and running local LLMs. Clean UI, no command line needed, runs fully offline.",                             "url": "https://lmstudio.ai",                         "tags": ["open-source", "local", "desktop"],     "image": FALLBACK_IMAGE},
    {"name": "Mistral AI",         "category": "Open-Source LLM",  "pricing": "freemium", "description": "French AI lab behind the Mistral and Mixtral open-weight models. Offers both open-source models and a fast API.",                                    "url": "https://mistral.ai",                          "tags": ["open-source", "llm", "api"],           "image": FALLBACK_IMAGE},
    {"name": "Meta Llama",         "category": "Open-Source LLM",  "pricing": "free",     "description": "Meta's family of open-weight large language models. Llama 3 rivals closed models on many benchmarks and is free to download and run.",               "url": "https://llama.meta.com",                      "tags": ["open-source", "meta", "llm"],          "image": FALLBACK_IMAGE},
    {"name": "Canva AI",           "category": "Design",            "pricing": "freemium", "description": "AI-powered design tools inside Canva — generate images, remove backgrounds, write copy and auto-resize designs for any format.",                     "url": "https://canva.com/ai-image-generator",        "tags": ["design", "image", "canva"],            "image": FALLBACK_IMAGE},
    {"name": "Adobe Firefly",      "category": "Design",            "pricing": "freemium", "description": "Adobe's family of creative AI tools for generating images, vectors and text effects. Trained on licensed content for commercial safety.",             "url": "https://firefly.adobe.com",                   "tags": ["design", "image", "adobe"],            "image": FALLBACK_IMAGE},
    {"name": "Ideogram",           "category": "Image Generation",  "pricing": "freemium", "description": "AI image generator that excels at generating text inside images accurately — great for logos, posters and social media graphics.",                   "url": "https://ideogram.ai",                         "tags": ["image", "text", "design"],             "image": FALLBACK_IMAGE},
]

AGENTS_FALLBACK: List[Dict] = [
    {"name": "AutoGPT",                 "type": "General agent",         "status": "Open-source", "description": "One of the first autonomous AI agents. Chains GPT-4 calls to complete long-horizon tasks without human input.",                                             "url": "https://github.com/Significant-Gravitas/AutoGPT",  "tags": ["autonomous", "gpt-4", "open-source"]},
    {"name": "Claude Computer Use",     "type": "Computer agent",        "status": "Beta",        "description": "Anthropic's agent that controls a computer — clicks buttons, types text and navigates browsers to complete tasks.",                                         "url": "https://docs.anthropic.com/computer-use",          "tags": ["anthropic", "desktop", "browser"]},
    {"name": "OpenAI Operator",         "type": "Web agent",             "status": "Available",   "description": "OpenAI's agent that navigates websites and completes multi-step tasks like booking, shopping and form filling.",                                             "url": "https://openai.com/operator",                      "tags": ["openai", "web", "automation"]},
    {"name": "LangChain Agents",        "type": "Framework",             "status": "Open-source", "description": "The most popular framework for building LLM agents with tool use, memory and multi-step reasoning chains.",                                                 "url": "https://www.langchain.com",                        "tags": ["framework", "python", "tool-use"]},
    {"name": "CrewAI",                  "type": "Multi-agent",           "status": "Open-source", "description": "Orchestrate multiple AI agents with distinct roles to collaborate on complex tasks like a real crew.",                                                      "url": "https://crewai.com",                               "tags": ["multi-agent", "python", "collaboration"]},
    {"name": "Microsoft Copilot Studio","type": "No-code agent builder", "status": "Available",   "description": "Build, configure and deploy AI agents without code inside Microsoft 365 and Power Platform ecosystems.",                                                    "url": "https://copilotstudio.microsoft.com",              "tags": ["microsoft", "no-code", "enterprise"]},
    {"name": "AgentGPT",                "type": "Browser agent",         "status": "Free",        "description": "Run autonomous AI agents in your browser. Define a goal and watch the agent break it into tasks and execute them.",                                         "url": "https://agentgpt.reworkd.ai",                      "tags": ["browser", "autonomous", "no-install"]},
    {"name": "Devin",                   "type": "Coding agent",          "status": "Available",   "description": "The first AI software engineer. Devin plans, codes, debugs and deploys software autonomously end-to-end.",                                                 "url": "https://devin.ai",                                 "tags": ["coding", "autonomous", "software-engineer"]},
    {"name": "BabyAGI",                 "type": "Task agent",            "status": "Open-source", "description": "A Python script that uses GPT-4 and vector DBs to autonomously create and execute a task list to achieve a goal.",                                         "url": "https://github.com/yoheinakajima/babyagi",         "tags": ["autonomous", "python", "open-source"]},
    {"name": "AutoGen",                 "type": "Multi-agent framework", "status": "Open-source", "description": "Microsoft Research framework where multiple agents converse to collaboratively solve tasks.",                                                               "url": "https://microsoft.github.io/autogen",              "tags": ["microsoft", "multi-agent", "framework"]},
    {"name": "Google Gemini Agents",    "type": "General agent",         "status": "Available",   "description": "Google Gemini-powered agents with access to Search, Maps, Gmail and Workspace tools.",                                                                     "url": "https://deepmind.google/technologies/gemini",      "tags": ["google", "multimodal", "search"]},
    {"name": "Phidata",                 "type": "Agent framework",       "status": "Open-source", "description": "Build AI agents with memory, knowledge and tools using a clean Python API. Supports any LLM provider.",                                                    "url": "https://phidata.com",                              "tags": ["python", "framework", "memory"]},
    {"name": "Claude Code",             "type": "Coding agent",          "status": "Available",   "description": "Anthropic agentic coding tool in your terminal. Understands entire codebases and executes multi-step engineering tasks.",                                   "url": "https://claude.ai/code",                           "tags": ["anthropic", "coding", "terminal"]},
    {"name": "Cursor Agent",            "type": "Coding agent",          "status": "Available",   "description": "Cursor built-in agent mode that autonomously writes, runs and debugs code across your entire project.",                                                    "url": "https://cursor.sh",                                "tags": ["coding", "vscode", "autonomous"]},
    {"name": "n8n AI Agents",           "type": "Workflow agent",        "status": "Open-source", "description": "Build visual AI agent workflows with open-source automation. Connect any tool, API or model with no code.",                                                "url": "https://n8n.io",                                   "tags": ["workflow", "automation", "no-code"]},
    {"name": "Zapier AI Agents",        "type": "Workflow agent",        "status": "Available",   "description": "Zapier AI agents connect your apps and automate complex multi-step workflows using natural language instructions.",                                         "url": "https://zapier.com/ai",                            "tags": ["workflow", "automation", "no-code"]},
]

COURSES: List[Dict] = [
    # Free / Freemium
    {
        "title":    "Generative AI for Everyone",
        "provider": "DeepLearning.AI",
        "platform": "Coursera",
        "level":    "Beginner",
        "pricing":  "free",
        "duration": "6 hrs",
        "tags":     ["genai", "beginner", "no-code"],
        "description": "Andrew Ng's non-technical intro to generative AI — how it works, where it can be applied, and how to use it in your own projects.",
        "url":      "https://www.coursera.org/learn/generative-ai-for-everyone",
        "cert":     True,
    },
    {
        "title":    "Introduction to Large Language Models",
        "provider": "Google Cloud",
        "platform": "Google Cloud Skills Boost",
        "level":    "Beginner",
        "pricing":  "free",
        "duration": "1 hr",
        "tags":     ["llm", "google", "beginner"],
        "description": "Quick but solid overview of LLMs — what they are, use cases, and how prompt tuning works. Part of Google's Generative AI learning path.",
        "url":      "https://cloudskillsboost.google/course_templates/539",
        "cert":     True,
    },
    {
        "title":    "ChatGPT Prompt Engineering for Developers",
        "provider": "DeepLearning.AI + OpenAI",
        "platform": "DeepLearning.AI",
        "level":    "Beginner",
        "pricing":  "free",
        "duration": "1 hr",
        "tags":     ["prompt-engineering", "openai", "python"],
        "description": "Hands-on short course by Isa Fulford and Andrew Ng. Learn prompt engineering best practices for building LLM-powered applications.",
        "url":      "https://www.deeplearning.ai/short-courses/chatgpt-prompt-engineering-for-developers/",
        "cert":     False,
    },
    {
        "title":    "LangChain for LLM Application Development",
        "provider": "DeepLearning.AI",
        "platform": "DeepLearning.AI",
        "level":    "Intermediate",
        "pricing":  "free",
        "duration": "1 hr",
        "tags":     ["langchain", "python", "llm"],
        "description": "Build LLM-powered apps using LangChain — covers chains, agents, memory and tools with Python code walkthroughs.",
        "url":      "https://www.deeplearning.ai/short-courses/langchain-for-llm-application-development/",
        "cert":     False,
    },
    {
        "title":    "Hugging Face NLP Course",
        "provider": "Hugging Face",
        "platform": "Hugging Face",
        "level":    "Intermediate",
        "pricing":  "free",
        "duration": "Self-paced",
        "tags":     ["nlp", "transformers", "python", "huggingface"],
        "description": "The definitive free course on Transformers and the Hugging Face ecosystem — fine-tuning, tokenizers, datasets and deployment.",
        "url":      "https://huggingface.co/learn/nlp-course",
        "cert":     False,
    },
    {
        "title":    "Elements of AI",
        "provider": "University of Helsinki",
        "platform": "elementsofai.com",
        "level":    "Beginner",
        "pricing":  "free",
        "duration": "30 hrs",
        "tags":     ["ai-fundamentals", "beginner", "no-code"],
        "description": "Finland's famous open online course covering AI fundamentals, machine learning basics and societal implications. No coding needed.",
        "url":      "https://www.elementsofai.com",
        "cert":     True,
    },
    {
        "title":    "Fast.ai — Practical Deep Learning for Coders",
        "provider": "fast.ai",
        "platform": "fast.ai",
        "level":    "Intermediate",
        "pricing":  "free",
        "duration": "Self-paced",
        "tags":     ["deep-learning", "python", "pytorch"],
        "description": "Top-down, code-first approach to deep learning. Covers vision, NLP and tabular models using PyTorch and the fastai library.",
        "url":      "https://course.fast.ai",
        "cert":     False,
    },
    {
        "title":    "CS50's Introduction to AI with Python",
        "provider": "Harvard University",
        "platform": "edX",
        "level":    "Intermediate",
        "pricing":  "free",
        "duration": "7 weeks",
        "tags":     ["python", "algorithms", "harvard"],
        "description": "Harvard's intro to AI concepts — search, knowledge, uncertainty, optimisation, machine learning, neural networks and NLP with Python.",
        "url":      "https://cs50.harvard.edu/ai/",
        "cert":     True,
    },
    # Paid / Certification
    {
        "title":    "AWS Certified AI Practitioner",
        "provider": "Amazon Web Services",
        "platform": "AWS Training",
        "level":    "Beginner",
        "pricing":  "paid",
        "duration": "Self-paced",
        "tags":     ["aws", "cloud", "certification"],
        "description": "AWS's foundational AI/ML certification. Covers AI/ML concepts, AWS AI services (Bedrock, SageMaker, Rekognition) and responsible AI.",
        "url":      "https://aws.amazon.com/certification/certified-ai-practitioner/",
        "cert":     True,
    },
    {
        "title":    "Google Professional Machine Learning Engineer",
        "provider": "Google Cloud",
        "platform": "Google Cloud",
        "level":    "Advanced",
        "pricing":  "paid",
        "duration": "Self-paced",
        "tags":     ["google-cloud", "mlops", "certification"],
        "description": "Professional-level cert for designing, building and productionising ML models on Google Cloud. Highly respected in the industry.",
        "url":      "https://cloud.google.com/learn/certification/machine-learning-engineer",
        "cert":     True,
    },
    {
        "title":    "Microsoft Azure AI Engineer Associate",
        "provider": "Microsoft",
        "platform": "Microsoft Learn",
        "level":    "Intermediate",
        "pricing":  "paid",
        "duration": "Self-paced",
        "tags":     ["azure", "microsoft", "certification"],
        "description": "Build and deploy AI solutions using Azure Cognitive Services, Azure OpenAI, and Azure ML. Leads to the AI-102 certification.",
        "url":      "https://learn.microsoft.com/en-us/credentials/certifications/azure-ai-engineer/",
        "cert":     True,
    },
    {
        "title":    "Deep Learning Specialization",
        "provider": "DeepLearning.AI",
        "platform": "Coursera",
        "level":    "Intermediate",
        "pricing":  "paid",
        "duration": "5 months",
        "tags":     ["deep-learning", "python", "tensorflow"],
        "description": "Andrew Ng's landmark 5-course series. Covers neural networks, CNNs, RNNs, LSTMs, transformers and practical ML projects.",
        "url":      "https://www.coursera.org/specializations/deep-learning",
        "cert":     True,
    },
    {
        "title":    "Machine Learning Specialization",
        "provider": "Stanford + DeepLearning.AI",
        "platform": "Coursera",
        "level":    "Beginner",
        "pricing":  "paid",
        "duration": "3 months",
        "tags":     ["ml", "python", "stanford"],
        "description": "Updated Andrew Ng ML course — supervised learning, unsupervised learning and best practices for building real ML systems.",
        "url":      "https://www.coursera.org/specializations/machine-learning-introduction",
        "cert":     True,
    },
    {
        "title":    "LLMOps: Building Real-World Applications",
        "provider": "DeepLearning.AI",
        "platform": "DeepLearning.AI",
        "level":    "Advanced",
        "pricing":  "free",
        "duration": "1 hr",
        "tags":     ["llmops", "mlops", "production"],
        "description": "Short course on deploying LLMs to production — data pipelines, model evaluation, monitoring and CI/CD for LLM-based applications.",
        "url":      "https://www.deeplearning.ai/short-courses/llmops/",
        "cert":     False,
    },
    {
        "title":    "AI Agents in LangGraph",
        "provider": "DeepLearning.AI",
        "platform": "DeepLearning.AI",
        "level":    "Intermediate",
        "pricing":  "free",
        "duration": "1 hr",
        "tags":     ["agents", "langgraph", "python"],
        "description": "Build agentic AI applications using LangGraph — covers state machines, tool use, human-in-the-loop and multi-agent systems.",
        "url":      "https://www.deeplearning.ai/short-courses/ai-agents-in-langgraph/",
        "cert":     False,
    },
    {
        "title":    "Prompt Engineering for Generative AI",
        "provider": "Vanderbilt University",
        "platform": "Coursera",
        "level":    "Beginner",
        "pricing":  "paid",
        "duration": "3 weeks",
        "tags":     ["prompt-engineering", "genai", "beginner"],
        "description": "Comprehensive prompt engineering course covering zero-shot, few-shot, chain-of-thought, ReAct and multimodal prompting techniques.",
        "url":      "https://www.coursera.org/learn/prompt-engineering",
        "cert":     True,
    },
    {
        "title":    "Databricks Generative AI Fundamentals",
        "provider": "Databricks",
        "platform": "Databricks Academy",
        "level":    "Beginner",
        "pricing":  "free",
        "duration": "2 hrs",
        "tags":     ["genai", "databricks", "certification"],
        "description": "Free accreditation from Databricks covering generative AI fundamentals, LLMs, RAG and responsible AI practices.",
        "url":      "https://www.databricks.com/learn/training/generative-ai-fundamentals-accreditation",
        "cert":     True,
    },
    {
        "title":    "Building RAG Agents with LLMs",
        "provider": "NVIDIA",
        "platform": "NVIDIA Deep Learning Institute",
        "level":    "Advanced",
        "pricing":  "paid",
        "duration": "1 day",
        "tags":     ["rag", "nvidia", "agents"],
        "description": "Hands-on workshop from NVIDIA on building retrieval-augmented generation systems and LLM-powered agents at scale.",
        "url":      "https://learn.nvidia.com/courses/course-detail?course_id=course-v1:DLI+S-FX-15+V1",
        "cert":     True,
    },
]
